services:
  mysql:
    image: mysql:8.0
    container_name: notes_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notes_db
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: notes_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: notesuser
      DB_PASSWORD: notespass
      DB_NAME: notes_db
      SECRET_KEY: ThisIsASecretKeyForJWTAuthenticationShouldBeLongAndRandom
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mysql_data: